# Generated by Django 2.1 on 2018-09-25 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('date', models.IntegerField()),
                ('time', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('url', models.TextField()),
                ('category', models.CharField(default='other', max_length=128)),
                ('image_url', models.TextField(default='#')),
                ('address', models.CharField(default='444 N Wabash St', max_length=128)),
                ('city', models.CharField(default='Chicago', max_length=128)),
                ('state', models.CharField(default='IL', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='dostuff.Category')),
                ('eventid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='dostuff.Event')),
            ],
        ),
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='dostuff.Category')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='dostuff.Event')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=64)),
                ('key', models.TextField(default='afkdjkajskfjaksjdfkajsdkfjaksdfjajfakkj323')),
                ('auth_key', models.CharField(default='kdsfk23r2k3jr2krj23r29rfskdfjsdf293f29fj', max_length=16)),
                ('last_login', models.IntegerField(default=0)),
                ('email', models.CharField(default='test', max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
