# Generated by Django 2.1 on 2018-09-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dostuff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='auth_key',
            field=models.CharField(default='dfjsdf293f29fj', max_length=16),
        ),
    ]
