# Generated by Django 2.1 on 2018-08-17 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dostuff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='dostuff.Event')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='dostuff.User')),
            ],
        ),
    ]
