# Generated by Django 2.1 on 2018-08-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dostuff', '0006_auto_20180821_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(default='other', max_length=64),
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(default='Chicago', max_length=64),
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.CharField(default='IL', max_length=64),
        ),
    ]
