# Generated by Django 2.1 on 2018-08-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dostuff', '0007_auto_20180821_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='address',
            field=models.CharField(default='444 N Wabash St', max_length=128),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(default='other', max_length=128),
        ),
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(default='Chicago', max_length=128),
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.CharField(default='IL', max_length=128),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.CharField(max_length=64),
        ),
    ]
