# Generated by Django 2.1 on 2018-09-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dostuff', '0008_auto_20180821_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='key',
            field=models.CharField(default='GJ7M2KTLZFNRM3ZRF30H9F7IBWY2VAINSAO04DVCKQ50NT8FOU3OZFO', max_length=64),
        ),
    ]
