# Generated by Django 2.1 on 2018-09-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dostuff', '0009_userprofile_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key',
            field=models.CharField(default='4ea43929d9a2c6e083618cf9386a62682298ba151bfe5c961e335909a4e03ff5a319cbc19c3e238b311a5b6a9a053e632a1f396ef8b949', max_length=64),
        ),
    ]
