# Generated by Django 2.1 on 2018-09-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dostuff', '0010_auto_20180921_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key',
            field=models.TextField(default='de046c715907c633813cd7865e5b47611b309a45760532f840731757405be08adb7984a3f1ccc3b2f65f52247c1fb6a86f64e68dcfb4c0'),
        ),
    ]
