# Generated by Django 2.1 on 2018-09-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dostuff', '0010_auto_20180921_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key',
            field=models.CharField(default='46213da11655baff3595a64a78df93f21420bb2cf726701047728df398083e5f2ea13a35590ecb0658c8e2e5e35a5a6d76a00625e3d9be', max_length=64),
        ),
    ]
