# Generated by Django 2.1 on 2018-09-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dostuff', '0011_auto_20180921_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key',
            field=models.CharField(default='b823bba4ee461eae4069d5b3a25591146cb7e8419abf9d763da661253ffab3da788e6898c12722f9b6746b00fe7c7df29e598fc0fc35b6', max_length=64),
        ),
    ]
