# Generated by Django 2.1 on 2018-09-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dostuff', '0011_auto_20180921_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auth_key',
            field=models.CharField(default='e09541f97aae', max_length=16),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_login',
            field=models.IntegerField(default=1537727206.488677),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key',
            field=models.TextField(default='89e46493644d98ed9d15a8c5a86f5f74c772b31ee5c2e002d5d9b56c517433bf3279b8975ee78a6077630447bd3bbb16bb9190f63ad87d'),
        ),
    ]
