# Generated by Django 2.1 on 2018-09-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dostuff', '0012_auto_20180923_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='auth_key',
            field=models.CharField(default='76a135699b20', max_length=16),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default='test', max_length=64),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key',
            field=models.TextField(default='f6d4ae59782816539cab6310d1e5dd437c204735b3c371339de3fd559d6b7de122052fd3e270f7bb6fa51d1e9b83965d8afac5d80b8460'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_login',
            field=models.IntegerField(default=1537800115.597055),
        ),
    ]
