# Generated by Django 2.1 on 2018-09-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dostuff', '0012_auto_20180921_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key',
            field=models.TextField(default='2f11961cc44794fba71445d666618ec26ff3164fdde62c11b68a7c9190e6d16c5faadf0a123a984454586fb8a3c6bf9b1944f73a4ea5b3'),
        ),
    ]
