# Generated by Django 2.1 on 2018-09-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dostuff', '0013_auto_20180924_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='auth_key',
            field=models.CharField(default='52ea07496a89', max_length=16),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key',
            field=models.TextField(default='49aafb6725f0681825f5ac4a42a068f1e9df53e6e1acc37a185b6ffdd500ca60bff287c6674e00e7a511d68dd11614caa8db5d3d8a51b4'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_login',
            field=models.IntegerField(default=1537800511.540542),
        ),
    ]
