# Generated by Django 2.1 on 2018-09-24 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dostuff', '0014_auto_20180924_1448'),
        ('dostuff', '0013_auto_20180921_1726'),
    ]

    operations = [
    ]
