# Generated by Django 2.1 on 2018-08-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dostuff', '0004_auto_20180818_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.TextField(),
        ),
    ]
