# Generated by Django 2.1 on 2018-08-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dostuff', '0005_auto_20180820_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(default='444 N Wabash St', max_length=64),
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(default='other', max_length=32),
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(default='Chicago', max_length=32),
        ),
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.TextField(default='#'),
        ),
        migrations.AddField(
            model_name='event',
            name='state',
            field=models.CharField(default='IL', max_length=32),
        ),
    ]
